// This file was automatically generated by the script 'find_files.py'
// Include directories in Verilog/SystemVerilog simulators locations
+incdir+./design
+incdir+./design/SPI_Assertions
+incdir+./design/SPI_design
+incdir+./design/SPI_design/Designer RTL
+incdir+./design/SPI_design/Golden Models
+incdir+./interface
+incdir+./top
+incdir+./top/test
+incdir+./top/test/enviroment
+incdir+./top/test/enviroment/coverage_collector
+incdir+./top/test/enviroment/ram_agent
+incdir+./top/test/enviroment/ram_agent/driver
+incdir+./top/test/enviroment/ram_agent/monitor
+incdir+./top/test/enviroment/ram_agent/sequencer
+incdir+./top/test/enviroment/scoreboard
+incdir+./top/test/enviroment/slave_agent
+incdir+./top/test/enviroment/slave_agent/driver
+incdir+./top/test/enviroment/slave_agent/monitor
+incdir+./top/test/enviroment/slave_agent/sequencer
// Enviroment source files
SPI_Assertions/SPI_ram_sva.sv
SPI_Assertions/SPI_slave_sva.sv
SPI_design/Designer RTL/SPI_ram.v
SPI_design/Designer RTL/SPI_slave.v
SPI_design/Designer RTL/design.v
SPI_design/Golden Models/dpi_golden_model.sv
SPI_design/Golden Models/golden_models.sv
SPI_design/Golden Models/ram_golden_model.sv
SPI_design/Golden Models/spi_sys_golden_model.sv
SPI_if.sv
shared_pkg.sv
spi_defines.svh
test/SPI_test_base.sv
test/SPI_test_pkg.sv
test/enviroment/SPI_env.sv
test/enviroment/SPI_env_pkg.sv
test/enviroment/coverage_collector/SPI_coverage_collector.sv
test/enviroment/ram_agent/SPI_ram_agent.sv
test/enviroment/ram_agent/SPI_ram_pkg.sv
test/enviroment/ram_agent/driver/SPI_ram_driver.sv
test/enviroment/ram_agent/monitor/SPI_ram_monitor.sv
test/enviroment/ram_agent/sequencer/SPI_ram_sequencer.sv
test/enviroment/scoreboard/SPI_scoreboard.sv
test/enviroment/slave_agent/SPI_slave_agent.sv
test/enviroment/slave_agent/SPI_slave_pkg.sv
test/enviroment/slave_agent/driver/SPI_slave_driver.sv
test/enviroment/slave_agent/monitor/SPI_slave_monitor.sv
test/enviroment/slave_agent/sequencer/SPI_slave_sequencer.sv
top.sv
